### ISSUE TITLE
calling 'reshape!' method of a view (fatal)

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#119]
Hello. 
 
```ruby
require 'numo/narray'

a = Numo::UInt8[1]
v = a.view
v.reshape!(1,1)
```
free(): invalid pointer
中止 (コアダンプ)

It may be a bug

**Comment by masa16** [comment]
Fixed: https://github.com/ruby-numo/numo-narray/commit/1b64388ea412306879bef0e7d63aaeda5d1903b4
Thank you for reporting.

**Comment by kojix2** [comment]
Thank you!
