### ISSUE TITLE
Flattening an empty narray (view) may cause an error.

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#127]
Hello!

```ruby
require 'numo/narray'

a = Numo::UInt8.ones(1)
b = a[a<0]
b.flatten
```

cause Segmentation fault.

**Comment by masa16** [comment]
Fixed. https://github.com/ruby-numo/numo-narray/commit/762dcbe4afba6a6f07e8b140143ee23f5072091f
Thanks.

**Comment by kojix2** [comment]
I checked it. Thank you!
