### ISSUE TITLE
Concatenate empty arrays

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#128]
Hello

I realized that an empty array could not be concatenated.

```ruby
require 'numo/narray'
a = Numo::DFloat.new(0)
b = Numo::DFloat.new(3).seq

a.concatenate b # RangeError (0...0 is out of range for size=3)
Numo::DFloat.hstack([a,b]) # same error
b.concatenate a # RangeError (3...3 is out of range for size=3)
Numo::DFloat.hstack([b,a]) # same error
```

Ruby Array can concatenate empty arrays.

```ruby
a = []
b = [0,1,2]
a.concat b
```

it seems that the method that change the size of the narray is written in Ruby, not C.
Methods related to `concatenate`, such as `Numo::SFloat.dstack`, can be very slow when used with Cumo. So, I don't think NArray needs to behave exactly like Ruby Array.  It's okay .

However, it might be useful to concatenate an empty array.

**Comment by masa16** [comment]
This issue is fixed, https://github.com/ruby-numo/numo-narray/commit/08bc8a77e3d36c3422b99de54a2a547a3def133a
But more work is needed to support numpy-like empty array.

```
>>> a = numpy.arange(6).reshape(2,3)
>>> a[:,0:1]
array([[0],
       [3]])
>>> a[:,0:0]
array([], shape=(2, 0), dtype=int64)
```

**Comment by kojix2** [comment]
Well, is this an empty array with the fixed shape?
I had never thought about it. Mathematics is always out of range for my brain size.
I think this issue has been resolved. Thank you.

**Comment by kojix2** [comment]
Ah, I understood your point.

```ruby
a = Numo::DFloat.new(2,2).seq
#=> Numo::DFloat#shape=[2,2]
#[[0, 1], 
# [2, 3]]

b = a[a<0]
# should be
# => Numo::DFloat#shape=[2,2](empty)

Numo::DFloat.dstack([a,b])
#=>Numo::DFloat#shape=[2,2]
#[[0, 1], 
# [2, 3]]
#or
#=>Numo::DFloat#shape=[2,2,1]
#[[[0], 
#  [1]], 
# [[2], 
#  [3]]]
```
I see. This may be useful.

**Comment by masa16** [comment]
Ah, already supported.

```ruby
> a = Numo::DFloat.new(2,2).seq
=> Numo::DFloat#shape=[2,2]
[[0, 1], 
 [2, 3]]

> b = a[0..0,0..]
=> Numo::DFloat(view)#shape=[1,2]
[[0, 1]]

> c = a[[],0..]
=> Numo::DFloat(view)#shape=[0,2][]

> Numo::DFloat.vstack([a,b,c])
=> Numo::DFloat#shape=[3,2]
[[0, 1], 
 [2, 3], 
 [0, 1]]
```
But not well tested.

BTW `a[a<0]` should return 1-dimensional array:

```ruby
> a = Numo::DFloat.new(2,2).seq
=> Numo::DFloat#shape=[2,2]
[[0, 1], 
 [2, 3]]

> a[a>0]
=> Numo::DFloat(view)#shape=[3]
[1, 2, 3]

> a[a<0]
=> Numo::DFloat(view)#shape=[0][]
```

**Comment by kojix2** [comment]
> BTW a[a<0] should return 1-dimensional array

I see...

```ruby
a[a>1]
# Numo::DFloat(view)#shape=[2]
# [2, 3]
```
shoud be 1-dimensional array. OK. I understand.
