### ISSUE TITLE
Sorting a 2D array. Strange behavior.

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#129]
I am trying to see how 2D array sorting works.
And I find these strange behaviors.

```ruby
require 'numo/narray'

a = Numo::DFloat.new(100).rand.sort_index
a = a.reshape 10, 10

p a.sort(1)
p a.sort(-2)
```
malloc(): memory corruption
中止 (コアダンプ)

```ruby
require 'numo/narray'

a = Numo::DFloat[0,3,2,1]
a = a.reshape(2,2)

p a.sort(-2)
```
Numo::DFloat#shape=[2,2]
[[0, 1], 
 [2.37152e-322, 3]]

```ruby
require 'numo/narray'

a = Numo::DFloat[0,3,2,1]
a = a.reshape(2,2)

p a.sort(0)
```
Numo::DFloat#shape=[2,2]
[[0, 1], 
 [4.65207e-310, 3]]

I'm sorry if this is a known issue and is currently under development. 
Thank you very much.

**Comment by masa16** [comment]
fixed with #129
