### ISSUE TITLE
How to convert Ruby Array to NArray ?

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#132]
Hello.

How do we convert a Ruby Array to Numo:: NArray?

The ways I know is,

```ruby
Numo::SFloat[*ar]
Numo::SFloat.cast(ar)
```

Is there any other recommended way?

NArray was designed for scientific computing. But with the success of Rumale, it's likely that more Web developers will use NArray in the future. So I want to be clear about how to convert a Ruby Array to NArray.

**Comment by masa16** [comment]
Yes, that's all.

**Comment by kojix2** [comment]
Thank you for your explanation!
