### ISSUE TITLE
Integration/synergies with SciRuby

### ISSUE THREAD

**Issue by edmundhighcock** [ruby-numo/numo-narray#15]
Hi all,

Nice to see that NArray is finally being developed again. However, it concerns me that a lot of the development here mirrors the development at SciRuby (http://sciruby.com/), and so users will need to make the choice between two different scientific ruby frameworks. Have you considered aiming for compatibility/integration with SciRuby?

Thanks,

Edmund

**Comment by kojix2** [comment]
SciRuby's NMatrix is no longer being developed. However, numo-narray continues to be developed. As far as I know, NMatrix is not as good as numo-narray in all aspects of performance, performance, and user experience.
I believe that numo-narray has become the standard for Ruby implementations of matrix computation.

**Comment by edmundhighcock** [comment]
Thanks! Nice to see that NArray is still alive!
