### ISSUE TITLE
Please release a new version that supports Ruby 2.7

### ISSUE THREAD

**Issue by yoshoku** [ruby-numo/numo-narray#150]
The installation of Numo::NArray fails in Ruby 2.7. 

```sh
$ gem install numo-narray
Fetching numo-narray-0.9.1.5.gem
Building native extensions. This could take a while...
ERROR:  Error installing numo-narray:
        ERROR: Failed to build gem native extension.
...

index.c:1056:44: error: too few arguments to function call, expected 4, have 3
    return rb_f_notimplement(argc,argv,self);
           ~~~~~~~~~~~~~~~~~
```

The installation succeeds on the master branch that contains supporting Ruby 2.7 (https://github.com/ruby-numo/numo-narray/pull/143). 
I would appreciate it if you could consider for releasing a new version.

**Comment by kojix2** [comment]
Maybe Tanaka-sensei is busy.
(#148) (#149)

I recommend Yoshoku to be the commiter of numo-narray.

**Comment by yoshoku** [comment]
The latest versions of Numo::NArray and Numo::Linalg have just been released. Thanks a lot!!
