### ISSUE TITLE
Fails to build on windows ruby26.3p62

### ISSUE THREAD

**Issue by dsisnero** [ruby-numo/numo-narray#152]
C:\Users\Dominic E Sisneros>systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Hewlett-Packard M70 Ver. 01.22, 5/21/2018

C:\Users\Dominic E Sisneros>ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]

C:\Users\Dominic E Sisneros>gem install numo-narray
c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/keycutter-1.0.0/lib/rubygems_plugin.rb:3: warning: constant Gem::RubyGemsVersion is deprecated
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing numo-narray:
        ERROR: Failed to build gem native extension.

    current directory: c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray
c:/Ruby26-x64/bin/ruby.exe -I c:/Ruby26-x64/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200121-6332-16dxt0q.rb extconf.rb
checking for stdbool.h... yes
checking for stdint.h... yes
checking for bool in stdbool.h... yes
checking for u_int8_t in stdint.h... no
checking for uint8_t in stdint.h... yes
checking for u_int16_t in stdint.h... no
checking for uint16_t in stdint.h... yes
checking for int32_t in stdint.h... yes
checking for u_int32_t in stdint.h... no
checking for uint32_t in stdint.h... yes
checking for int64_t in stdint.h... yes
checking for u_int64_t in stdint.h... no
checking for uint64_t in stdint.h... yes
checking for exp10()... no
checking for rb_arithmetic_sequence_extract()... yes
checking for rb_cComplex... yes
creating c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/numo/extconf.h
creating Makefile

current directory: c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray
make "DESTDIR=" clean

current directory: c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray
make "DESTDIR="
compiling narray.c
compiling array.c
compiling step.c
compiling index.c
compiling ndloop.c
compiling data.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_bit.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/bit.rb
compiling t_bit.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_int8.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/int8.rb
compiling t_int8.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_int16.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/int16.rb
compiling t_int16.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_int32.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/int32.rb
compiling t_int32.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_int64.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/int64.rb
compiling t_int64.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_uint8.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/uint8.rb
compiling t_uint8.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_uint16.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/uint16.rb
compiling t_uint16.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_uint32.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/uint32.rb
compiling t_uint32.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_uint64.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/uint64.rb
compiling t_uint64.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_sfloat.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/sfloat.rb
compiling t_sfloat.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_dfloat.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/dfloat.rb
compiling t_dfloat.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_scomplex.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/scomplex.rb
compiling t_scomplex.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_dcomplex.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/dcomplex.rb
compiling t_dcomplex.c
ruby c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/cogen.rb -l -o t_robject.c c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6/ext/numo/narray/gen/def/robject.rb
compiling t_robject.c
compiling math.c
compiling SFMT.c
compiling struct.c
compiling rand.c
linking shared-object numo/narray.so
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ndloop.o:ndloop.c:(.text+0x3fe6): undefined reference to `__chk_fail'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: t_bit.o:t_bit.c:(.text+0x7fa0): undefined reference to `__chk_fail'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: t_bit.o:t_bit.c:(.text+0x8049): undefined reference to `__chk_fail'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: t_bit.o:t_bit.c:(.text+0x826a): undefined reference to `__chk_fail'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: t_int8.o:t_int8.c:(.text+0xac5e): undefined reference to `__chk_fail'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: t_int8.o:t_int8.c:(.text+0xacf1): more undefined references to `__chk_fail' follow
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:362: narray.so] Error 1

make failed, exit code 2

Gem files will remain installed in c:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/numo-narray-0.9.1.6 for inspection.
Results logged to c:/Ruby26-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/numo-narray-0.9.1.6/gem_make.out

**Comment by masa16** [comment]
Compilation of numo-narray succeeds with 
```
ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
```
How about updating Ruby version?

**Comment by dsisnero** [comment]
Thanks, I updated ruby version and it worked!

Dominic
