### ISSUE TITLE
[Proposal] Change behavior of [] when ndim > 1

### ISSUE THREAD

**Issue by ankane** [ruby-numo/numo-narray#155]
Hi, thanks for this great project!

I wanted to get your thoughts on changing the behavior of `[]` to match both Ruby arrays and Numpy when `ndim` > 1. Currently, Numo returns a single value with `[]` regardless of the number of dimensions. It's easier to demonstrate on a 2d array.

```ruby
require "numo/narray"

a = Numo::NArray.asarray([[1, 2, 3], [4, 5, 6]])
p a[0] # 1
```

With Ruby arrays, you get an array back (the entire row).

```ruby
b = [[1, 2, 3], [4, 5, 6]]
p b[0] # [1, 2, 3]
```

Same with NumPy.

```py
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x[0]) # [1 2 3]
```

I personally find the Ruby array/NumPy behavior much more intuitive. Let me know your thoughts. This change would not be backwards compatible.

**Comment by kojix2** [comment]
Hello. According to Twitter, Tanaka-san is busy moving from Ibaraki Prefecture to Kanagawa Prefecture these days. :truck: :truck: :truck: 
I think he will reply when things settle down...

**Comment by ankane** [comment]
Thanks @kojix2. Was also going to suggest making `mean` work on integer types, but saw you already suggested it last year :) https://github.com/ruby-numo/numo-narray/issues/79

**Comment by orlando-labs** [comment]
Hi, @kojix2. Hello, @ankane. This proposal needs a bump indeed. Current behaviour is totally counterintuitive. I may contribute with the code, but we all need a permission to implement such breaking changes.

**Comment by ankane** [comment]
Cleaning up stale issues
