### ISSUE TITLE
Idea: Support casting any object that responds to `to_a`

### ISSUE THREAD

**Issue by ankane** [ruby-numo/numo-narray#157]
Hi, small thing, but it'd be great if `cast` worked with any object that responds to `to_a`. Currently, it throws `TypeError: invalid type for NArray`. Here's an example with Daru:

```ruby
require "daru"
require "numo/narray"

v = Daru::Vector.new([1, 2, 3])
Numo::NArray.cast(v.to_a) # success
Numo::NArray.cast(v)      # error
```

**Comment by masa16** [comment]
Your idea is implemented: https://github.com/ruby-numo/numo-narray/commit/29c5c1340c1e52f541a8055b14a87d521e10c62b

**Comment by ankane** [comment]
Thanks @masa16! However, I'm still seeing `TypeError: invalid type for NArray` with the example above in 0.9.1.8.

**Comment by ankane** [comment]
Thanks @masa16, looks like that last commit fixed it!
