### ISSUE TITLE
Error installing on windows

### ISSUE THREAD

**Issue by dsisnero** [ruby-numo/numo-narray#161]
C:\Users\Dominic E Sisneros\source\repos\ruby\try_ripper>gem update numo-narray
Updating installed gems
Updating numo-narray
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing numo-narray:
        ERROR: Failed to build gem native extension.

    current directory: c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/numo-narray-0.9.1.7/ext/numo/narray
c:/Ruby27-x64/bin/ruby.exe -I c:/Ruby27-x64/lib/ruby/2.7.0 -r ./siteconf20200505-23500-j3p3c6.rb extconf.rb
checking for stdbool.h... yes
checking for stdint.h... yes
checking for bool in stdbool.h... yes
checking for u_int8_t in stdint.h... no
checking for uint8_t in stdint.h... yes
checking for u_int16_t in stdint.h... no
checking for uint16_t in stdint.h... yes
checking for int32_t in stdint.h... yes
checking for u_int32_t in stdint.h... no
checking for uint32_t in stdint.h... yes
checking for int64_t in stdint.h... yes
checking for u_int64_t in stdint.h... no
checking for uint64_t in stdint.h... yes
checking for exp10()... no
checking for rb_arithmetic_sequence_extract()... yes
checking for rb_cComplex... yes
creating c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/numo-narray-0.9.1.7/ext/numo/narray/numo/extconf.h
creating Makefile

current directory: c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/numo-narray-0.9.1.7/ext/numo/narray
make "DESTDIR=" clean

current directory: c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/numo-narray-0.9.1.7/ext/numo/narray
make "DESTDIR="
compiling narray.c
compiling array.c
In file included from C:/Ruby27-x64/include/ruby-2.7.0/ruby.h:33,
                 from array.c:6:
array.c: In function 'na_object_type':
array.c:56:36: error: 'id_ge' undeclared (first use in this function); did you mean 'id_le'?
   56 |                 RTEST(rb_funcall(v,id_ge,1,int32_min))) {
      |                                    ^~~~~
C:/Ruby27-x64/include/ruby-2.7.0/ruby/ruby.h:479:31: note: in definition of macro 'RB_TEST'
  479 | #define RB_TEST(v) !(((VALUE)(v) & (VALUE)~RUBY_Qnil) == 0)
      |                               ^
array.c:56:17: note: in expansion of macro 'RTEST'
   56 |                 RTEST(rb_funcall(v,id_ge,1,int32_min))) {
      |                 ^~~~~
array.c:56:23: note: in expansion of macro 'rb_funcall'
   56 |                 RTEST(rb_funcall(v,id_ge,1,int32_min))) {
      |                       ^~~~~~~~~~
array.c:56:36: note: each undeclared identifier is reported only once for each function it appears in
   56 |                 RTEST(rb_funcall(v,id_ge,1,int32_min))) {
      |                                    ^~~~~
C:/Ruby27-x64/include/ruby-2.7.0/ruby/ruby.h:479:31: note: in definition of macro 'RB_TEST'
  479 | #define RB_TEST(v) !(((VALUE)(v) & (VALUE)~RUBY_Qnil) == 0)
      |                               ^
array.c:56:17: note: in expansion of macro 'RTEST'
   56 |                 RTEST(rb_funcall(v,id_ge,1,int32_min))) {
      |                 ^~~~~
array.c:56:23: note: in expansion of macro 'rb_funcall'
   56 |                 RTEST(rb_funcall(v,id_ge,1,int32_min))) {
      |                       ^~~~~~~~~~
make: *** [Makefile:345: array.o] Error 1

make failed, exit code 2

Gem files will remain installed in c:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/numo-narray-0.9.1.7 for inspection.
Results logged to c:/Ruby27-x64/lib/ruby/gems/2.7.0/extensions/x64-mingw32/2.7.0/numo-narray-0.9.1.7/gem_make.out
Gems updated: numo-narray

C:\Users\Dominic E Sisneros\source\repos\ruby\try_ripper>
[gem_make - Copy.out.txt](https://github.com/ruby-numo/numo-narray/files/4581423/gem_make.-.Copy.out.txt)

**Comment by masa16** [comment]
Thank you. Released new version.
