### ISSUE TITLE
Median incorrect for integer types

### ISSUE THREAD

**Issue by ankane** [ruby-numo/numo-narray#165]
Hey, it looks like `median` always returns integers for integer types, even when the true median is not an integer.

```ruby
require "numo/narray"

p Numo::NArray.cast([1.0, 2]).median # 1.5 - good
p Numo::NArray.cast([1, 2]).median   # 1 :(
```

Equivalent NumPy behavior

```py
import numpy as np

print(np.median(np.array([1.0, 2]))) # 1.5 - good
print(np.median(np.array([1, 2])))   # 1.5 - good
```

**Comment by masa16** [comment]
I followed Ruby's policy that an arithmetic operation returns same data type:
```
$ ruby -e 'p 3/2'
1
$ python3 -c 'print(3/2)'
1.5
```
But it may be better for median to return Float.

**Comment by ankane** [comment]
That'd be my vote fwiw. I can see it making sense for arithmetic (even though I wish Ruby behaved differently), but less so for other operations.
