### ISSUE TITLE
Can't reshape to ndim 0

### ISSUE THREAD

**Issue by ankane** [ruby-numo/numo-narray#166]
Trying to reshape to a 0-dimensional array raises `ArgumentError: No argrument` (with a small typo)

```ruby
require "numo/narray"

x = Numo::NArray.cast([1])
p x.ndim
x2 = x.reshape # fails
p x2.ndim
```

**Comment by masa16** [comment]
numo-narray does not support creating 0-dimensional array. Why do you think you require 0-dimensional array?

**Comment by ankane** [comment]
It's possible to create a 0-dimensional array, so I thought Numo supported it.

```ruby
x = Numo::NArray.cast(1)
x.ndim  # 0
x.shape # []
```

I ran into this while writing tests for [Npy](https://github.com/ankane/npy), which loads NumPy files.
