### ISSUE TITLE
How to compile and install numo-narray? (current status)

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#178]
Hello. @masa16 and numo-narray developers.

I hope that many people around the world will discover numo-narray and become its developers. I can't write C, so I can't develop numo-narray. But, I tried to compile numo-narray from the source code.

The README says `ruby setup.rb`. I ran this script, but it told me that I was missing some arguments. 
The script was last updated five years ago, and I suspected that it was no longer in use.

In practice, `rake compile` and `rake install` seem to be sufficient. What is the currently recommended way to develop numo-narray?

**Comment by nerdinand** [comment]
Take a look at https://github.com/ruby-numo/numo-narray/blob/master/.github/workflows/build.yml, that might help you...

**Comment by kojix2** [comment]
I see. It's true.

Indeed, looking at `travis.yml` and `github actions`, it seems that `ruby setup.rb` is obsolete.

Perhaps we need to update the description in README.
