### ISSUE TITLE
Release for Ruby 3.0

### ISSUE THREAD

**Issue by nerdinand** [ruby-numo/numo-narray#180]
Hi there

Would it be possible to release this gem for Ruby 3.0 as well? It can't be installed there currently, because the gemspec forbids it.
I built it locally for Ruby 3.0 and all the tests passed. This is all I changed:

```diff
--- a/numo-narray.gemspec
+++ b/numo-narray.gemspec
@@ -20,7 +20,7 @@ Gem::Specification.new do |spec|
   spec.summary       = %q{alpha release of Numo::NArray - New NArray class library in Ruby/Numo (NUmerical MOdule)}
   spec.homepage      = "https://github.com/ruby-numo/numo-narray"
   spec.license       = "BSD-3-Clause"
-  spec.required_ruby_version = '>= 2.2'
+  spec.required_ruby_version = '>= 3.0'
 
   spec.files         = `git ls-files Gemfile README.md Rakefile lib ext numo-narray.gemspec spec`.split($/)
   spec.executables   = spec.files.grep(%r{^bin/}) { |f| File.basename(f) }
```

**Comment by kojix2** [comment]
On my local environment, `gem install numo-narray` works fine.
* Ubuntu 20.04.1 LTS (Focal Fossa)
* ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

So I think it would be better to describe your environment in more detail.

**Comment by nerdinand** [comment]
Ah ok. I was on 0.9.1.8 still, not on 0.9.1.9. It works with the latest version. Thanks!
